// <auto-generated />
using System;
using EnergyScore.Persistence.DBConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnergyScore.Persistence.Migrations
{
    [DbContext(typeof(DbConnect))]
    [Migration("20250204125946_makeConnection")]
    partial class makeConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnergyScore.Domain.Entityies.About", b =>
                {
                    b.Property<Guid>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("averageCeilingHeight")
                        .HasColumnType("integer");

                    b.Property<int>("azimuthOfFrontOfHome")
                        .HasColumnType("integer");

                    b.Property<int>("conditionedBuildingVolume")
                        .HasColumnType("integer");

                    b.Property<int>("conditionedFloorArea")
                        .HasColumnType("integer");

                    b.Property<int>("numberofBedrooms")
                        .HasColumnType("integer");

                    b.Property<int>("numberofConditionedFloorsAboveGrade")
                        .HasColumnType("integer");

                    b.Property<string>("orientationOfFrontOfHome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("residentialFacilityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("yearBuilt")
                        .HasColumnType("integer");

                    b.HasKey("AboutId");

                    b.ToTable("About");
                });

            modelBuilder.Entity("EnergyScore.Domain.Entityies.Address", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Zipcode")
                        .HasColumnType("integer");

                    b.HasKey("AddressId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("EnergyScore.Domain.Entityies.AirInfiltrationMeasurement", b =>
                {
                    b.Property<Guid>("AirInfiltrationMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("uuid");

                    b.Property<int>("AirLeakage")
                        .HasColumnType("integer");

                    b.Property<int>("HousePressure")
                        .HasColumnType("integer");

                    b.Property<string>("LeakinessDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitofMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AirInfiltrationMeasurementId");

                    b.HasIndex("AboutId");

                    b.ToTable("AirInfiltrationMeasurement");
                });

            modelBuilder.Entity("EnergyScore.Domain.Entityies.AirInfiltrationMeasurement", b =>
                {
                    b.HasOne("EnergyScore.Domain.Entityies.About", "About")
                        .WithMany("AirInfiltrationMeasurements")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("EnergyScore.Domain.Entityies.About", b =>
                {
                    b.Navigation("AirInfiltrationMeasurements");
                });
#pragma warning restore 612, 618
        }
    }
}
